version: 2
updates:
  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "composer"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      # Group Laravel dependencies together
      laravel:
        patterns:
          - "illuminate/*"
          - "laravel/*"
      # Group development dependencies together
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "phpstan/*"
          - "pestphp/*"
          - "phpunit/*"